"""empty message

Revision ID: 8ad0ec96ac9a
Revises: 
Create Date: 2025-07-23 22:53:54.148978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad0ec96ac9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('insert_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('addresses_pkey')),
    sa.UniqueConstraint('address', name=op.f('addresses_address_key')),
    sa.UniqueConstraint('uuid', name=op.f('addresses_uuid_key'))
    )
    op.create_table('transactions',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('to_address', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(asdecimal=True), nullable=False),
    sa.Column('insert_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('transactions_pkey')),
    sa.UniqueConstraint('tx_hash', name=op.f('transactions_tx_hash_key')),
    sa.UniqueConstraint('uuid', name=op.f('transactions_uuid_key'))
    )
    op.create_table('transfers',
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('tx_hash', sa.String(length=100), nullable=False),
    sa.Column('from_address', sa.String(length=100), nullable=False),
    sa.Column('to_address', sa.String(length=100), nullable=False),
    sa.Column('asset', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Float(asdecimal=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('gas_used', sa.Float(asdecimal=True), nullable=False),
    sa.Column('gas_price', sa.Float(asdecimal=True), nullable=False),
    sa.Column('insert_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('transfers_pkey')),
    sa.UniqueConstraint('tx_hash', name=op.f('transfers_tx_hash_key')),
    sa.UniqueConstraint('uuid', name=op.f('transfers_uuid_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfers')
    op.drop_table('transactions')
    op.drop_table('addresses')
    # ### end Alembic commands ###